// Images Alt Prompt Generator for Web App - Matching Extension Format

interface ImageNode {
	url: string;
	alt: string | null;
	status: "with-alt" | "missing-alt" | "empty-alt";
	width?: number;
	height?: number;
	selector?: string;
}

export interface ImagesAltPromptContext {
	pageUrl: string;
	images: ImageNode[];
	summary: {
		total: number;
		withAlt: number;
		emptyAlt: number;
		missingAlt: number;
	};
	includeWithAlt: boolean;
	includeMissingAlt: boolean;
	includeEmptyAlt: boolean;
	includeDimensions?: boolean;
	includeSelectors?: boolean;
}

/**
 * Filter images based on context options
 */
function filterImages(context: ImagesAltPromptContext): ImageNode[] {
	return context.images.filter((img) => {
		if (img.status === "with-alt" && context.includeWithAlt) return true;
		if (img.status === "missing-alt" && context.includeMissingAlt)
			return true;
		if (img.status === "empty-alt" && context.includeEmptyAlt) return true;
		return false;
	});
}

/**
 * Format summary statistics
 */
function formatSummary(context: ImagesAltPromptContext): string {
	return `- Total Images: ${context.summary.total}
- With Alt Text: ${context.summary.withAlt}
- Missing Alt: ${context.summary.missingAlt}
- Empty Alt: ${context.summary.emptyAlt}`;
}

/**
 * Format images for platform prompt (ChatGPT, Claude)
 */
function formatImagesForPlatform(context: ImagesAltPromptContext): string {
	const images = filterImages(context);

	return images
		.map((img, index) => {
			let line = `\n${index + 1}. ${img.url}`;
			if (context.includeDimensions && img.width && img.height) {
				line += `\n   Dimensions: ${img.width}x${img.height}`;
			}
			if (img.status === "missing-alt") {
				line += "\n   Issue: Missing alt text";
			} else if (img.status === "empty-alt") {
				line += "\n   Issue: Empty alt text";
			} else if (context.includeWithAlt && img.alt) {
				line += `\n   Current alt: "${img.alt}"`;
			}
			return line;
		})
		.join("\n");
}

/**
 * Format images for IDE prompt (includes selectors)
 */
function formatImagesForIDE(context: ImagesAltPromptContext): string {
	const images = filterImages(context);

	return images
		.map((img, index) => {
			let line = `\n${index + 1}. ${img.url}`;
			if (context.includeDimensions && img.width && img.height) {
				line += `\n   Dimensions: ${img.width}x${img.height}`;
			}
			if (img.status === "missing-alt") {
				line += "\n   Issue: Missing alt text";
			} else if (img.status === "empty-alt") {
				line += "\n   Issue: Empty alt text";
			} else if (context.includeWithAlt && img.alt) {
				line += `\n   Current alt: "${img.alt}"`;
			}
			if (context.includeSelectors && img.selector) {
				line += `\n   Selector: ${img.selector}`;
			}
			return line;
		})
		.join("\n");
}

/**
 * Generate platform prompt (for ChatGPT, Claude, etc.) - EXACT EXTENSION FORMAT
 */
export function generateImagesAltPlatformPrompt(
	context: ImagesAltPromptContext,
): string {
	const images = filterImages(context);

	if (images.length === 0) {
		return `You are an SEO and accessibility expert. I need help fixing image alt text issues on my website.

**Website URL**: ${context.pageUrl}

**Current Status**:
${formatSummary(context)}

**No issues found matching your criteria.** Your image alt text is looking good!

═══════════════════════════════════════
Generated by webclarity.ai
═══════════════════════════════════════`;
	}

	return `You are an SEO and accessibility expert. I need help fixing image alt text issues on my website.

**Website URL**: ${context.pageUrl}

**Current Status**:
${formatSummary(context)}

**Instructions**:
- Review the images listed below
- Provide specific, descriptive alt text for each image
- Follow accessibility best practices (concise, descriptive, contextual)
- Consider SEO value without keyword stuffing
- DO NOT group images by category or type
- Provide results in strict numerical order matching the list below

**Images to Fix**:
${formatImagesForPlatform(context)}

═══════════════════════════════════════

Please provide improved alt text for each image. Use this EXACT format:

**Recommended Alt Text Fixes**

1. Alt Text: [improved alt text for image 1]
   Image Name: [filename.ext from URL]
   Image URL: [image URL 1]

2. Alt Text: [improved alt text for image 2]
   Image Name: [filename.ext from URL]
   Image URL: [image URL 2]

3. Alt Text: [improved alt text for image 3]
   Image Name: [filename.ext from URL]
   Image URL: [image URL 3]

(continue for all images)

Do NOT group images. Do NOT add categories. Just provide numbered alt text suggestions with their corresponding image names and URLs matching the exact order above.

IMPORTANT: After providing all alt text fixes, you MUST end your response with the following footer (include the dividers):

═══════════════════════════════════════
Generated by webclarity.ai
═══════════════════════════════════════`;
}

/**
 * Generate IDE prompt (for VS Code, Cursor, etc.) - EXACT EXTENSION FORMAT
 */
export function generateImagesAltIDEPrompt(
	context: ImagesAltPromptContext,
): string {
	const images = filterImages(context);

	if (images.length === 0) {
		return `You are an AI coding assistant. I need you to fix image alt text issues in my project files.

**CRITICAL INSTRUCTIONS:**
- DO NOT create any new files (no .md, no README, no documentation files)
- ONLY modify existing HTML/template files to add or update alt attributes
- After making all changes, provide a CHAT RESPONSE summarizing what was fixed

**Website URL**: ${context.pageUrl}

**Current Issues**:
${formatSummary(context)}

**No issues found matching your criteria.** Your image alt text is looking good!

═══════════════════════════════════════
Generated by webclarity.ai
═══════════════════════════════════════`;
	}

	return `You are an AI coding assistant. I need you to fix image alt text issues in my project files.

**CRITICAL INSTRUCTIONS:**
- DO NOT create any new files (no .md, no README, no documentation files)
- ONLY modify existing HTML/template files to add or update alt attributes
- After making all changes, provide a CHAT RESPONSE summarizing what was fixed

**Website URL**: ${context.pageUrl}

**Current Issues**:
${formatSummary(context)}

**Images to Fix (with CSS selectors to locate them)**:
${formatImagesForIDE(context)}

═══════════════════════════════════════

**YOUR TASK:**
1. For each image listed above, find the corresponding <img> element in the codebase using the provided CSS selector or image URL
2. Add or update the alt attribute with appropriate descriptive text
3. DO NOT create any new files

**AFTER COMPLETING ALL FIXES, provide a chat summary using this EXACT format:**

**Summary of Image Alt Text Fixes**

Total Images Fixed: [number]

File Modified:
- [file path]

**Alt Text Added:**

1. Alt Text: "[alt text for image 1]"
   Image Name: [filename.ext from URL]
   Image URL: [image URL 1]

2. Alt Text: "[alt text for image 2]"
   Image Name: [filename.ext from URL]
   Image URL: [image URL 2]

3. Alt Text: "[alt text for image 3]"
   Image Name: [filename.ext from URL]
   Image URL: [image URL 3]

(continue for ALL images in strict numerical order)

Do NOT group images by category. Do NOT add headings like "Navigation Logo" or "Service Icons". Just provide a flat numbered list with image names and URLs matching the exact order of images above.

**IMPORTANT:** Include this footer ONLY in your chat summary response, NOT in any code changes:
═══════════════════════════════════════
Generated by webclarity.ai
═══════════════════════════════════════`;
}
