// Images Alt Export Text Generator

interface ImageNode {
	url: string;
	alt: string | null;
	status: "with-alt" | "missing-alt" | "empty-alt";
	width?: number;
	height?: number;
	selector?: string;
}

export interface ExportOptions {
	includeWithAlt?: boolean;
	includeWithoutAlt?: boolean;
	includeDimensions?: boolean;
	includeSelectors?: boolean;
	includeSummary?: boolean;
}

interface ExportContext {
	images: ImageNode[];
	summary: {
		total: number;
		withAlt: number;
		emptyAlt: number;
		missingAlt: number;
	};
	pageUrl: string;
	options: ExportOptions;
}

/**
 * Filter images based on options
 */
function filterImages(
	images: ImageNode[],
	options: ExportOptions,
): ImageNode[] {
	return images.filter((img) => {
		if (img.status === "with-alt" && options.includeWithAlt !== false) {
			return true;
		}
		if (
			(img.status === "missing-alt" || img.status === "empty-alt") &&
			options.includeWithoutAlt !== false
		) {
			return true;
		}
		return false;
	});
}

/**
 * Get status label
 */
function getStatusLabel(status: string): string {
	const labels: Record<string, string> = {
		"with-alt": "✓ Has Alt Text",
		"missing-alt": "✗ Missing Alt Text",
		"empty-alt": "⚠ Empty Alt Text",
	};
	return labels[status] || status;
}

/**
 * Generate full text report
 */
export function generateFullReport(context: ExportContext): string {
	const { images, summary, pageUrl, options } = context;
	const filteredImages = filterImages(images, options);

	const lines: string[] = [
		"═══════════════════════════",
		"IMAGE ALT TEXT REPORT",
		"═══════════════════════════",
		`Generated: ${new Date().toLocaleString()}`,
		`URL: ${pageUrl || "Unknown"}`,
		"",
	];

	// Add summary section if enabled
	if (options.includeSummary !== false) {
		lines.push("───────────────────────────");
		lines.push("SUMMARY");
		lines.push("───────────────────────────");
		lines.push(`  Total Images:         ${summary.total}`);
		lines.push(`  With Alt Text:        ${summary.withAlt}`);
		lines.push(`  Missing Alt Text:     ${summary.missingAlt}`);
		lines.push(`  Empty Alt Text:       ${summary.emptyAlt}`);
		lines.push(`  Included in Report:   ${filteredImages.length}`);
		lines.push("");
	}

	lines.push("───────────────────────────");
	lines.push("IMAGE DETAILS");
	lines.push("───────────────────────────");
	lines.push("");

	// Add image details
	if (filteredImages.length === 0) {
		lines.push("  (No images match the selected filters)");
	} else {
		filteredImages.forEach((img, index) => {
			lines.push(`${index + 1}. ${getStatusLabel(img.status)}`);
			lines.push(`   URL: ${img.url}`);
			lines.push(`   Alt: ${img.alt || "(none)"}`);

			if (options.includeDimensions && (img.width || img.height)) {
				lines.push(
					`   Dimensions: ${img.width || "?"}×${img.height || "?"}`,
				);
			}

			if (options.includeSelectors && img.selector) {
				lines.push(`   Selector: ${img.selector}`);
			}

			// Add recommendation based on status
			if (img.status === "missing-alt") {
				lines.push(
					"   Recommendation: Add descriptive alt text for accessibility and SEO",
				);
			} else if (img.status === "empty-alt") {
				lines.push(
					"   Recommendation: Add meaningful alt text or confirm this is a decorative image",
				);
			}

			lines.push("");
		});
	}

	lines.push("───────────────────────────");
	lines.push("ALT TEXT BEST PRACTICES");
	lines.push("───────────────────────────");
	lines.push("  • Describe what's in the image and its purpose");
	lines.push("  • Be specific and accurate");
	lines.push("  • Keep it concise (10-125 characters recommended)");
	lines.push("  • Use keywords naturally if relevant");
	lines.push('  • For decorative images, use alt="" (empty string)');
	lines.push('  • Don\'t start with "image of" or "picture of"');
	lines.push("");

	lines.push("═══════════════════════════");
	lines.push("Generated by WebClarity.ai");
	lines.push("═══════════════════════════");

	return lines.join("\n");
}

/**
 * Generate filename for export
 */
export function generateExportFilename(): string {
	const date = new Date().toISOString().split("T")[0];
	return `images-alt-report-${date}.txt`;
}
